# Generated by Django 2.2 on 2019-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('userID', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('assign', models.CharField(max_length=10)),
                ('volunteer', models.CharField(max_length=16)),
                ('checked', models.CharField(max_length=5)),
            ],
        ),
    ]
