# Generated by Django 2.2 on 2019-05-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='address',
        ),
        migrations.AddField(
            model_name='case',
            name='addressAlley',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='addressCounty',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='addressDistrict',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='addressFloor',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='addressLane',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='addressNumber',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='addressRoad',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='addressRoom',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='case',
            name='assign',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='checked',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='case',
            name='email',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='phone',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='relation',
            field=models.CharField(default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='userID',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='volunteer',
            field=models.CharField(default='none', max_length=16),
        ),
    ]
