# Generated by Django 2.2 on 2019-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_auto_20190509_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='address',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
