# Generated by Django 2.2 on 2019-05-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0010_auto_20190510_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='userID',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='case',
            name='email',
        ),
        migrations.AddField(
            model_name='case',
            name='ID',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='addressSection',
            field=models.CharField(default='none', max_length=2),
        ),
        migrations.AddField(
            model_name='case',
            name='buildingAge',
            field=models.CharField(default='none', max_length=3),
        ),
        migrations.AddField(
            model_name='case',
            name='buildingRemarks',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='buildingType',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='date',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
