# Generated by Django 2.2 on 2019-05-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0011_auto_20190514_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='ID',
            new_name='TWID',
        ),
    ]
