# Generated by Django 2.2 on 2019-05-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0013_auto_20190514_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='TwID',
            new_name='TWID',
        ),
        migrations.AlterField(
            model_name='case',
            name='addressSection',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='case',
            name='buildingAge',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='case',
            name='buildingRemarks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='buildingType',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
