# Generated by Django 2.2 on 2019-05-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0015_auto_20190514_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='date',
            new_name='wishDate',
        ),
        migrations.AddField(
            model_name='case',
            name='applyDate',
            field=models.CharField(default='undefined', max_length=60),
        ),
    ]
