# Generated by Django 2.2 on 2019-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0016_auto_20190514_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='SN',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
