# Generated by Django 2.2 on 2019-05-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0017_case_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='TWID',
            new_name='lineID',
        ),
    ]
