# Generated by Django 2.2 on 2019-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0018_auto_20190518_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='buildingFloors',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
