# Generated by Django 2.2 on 2019-05-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0020_auto_20190519_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='addressFloorD',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='addressNumberD',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
