# Generated by Django 2.2 on 2019-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0021_auto_20190528_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='addressFloorD',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='case',
            name='addressNumberD',
            field=models.CharField(max_length=5),
        ),
    ]
