# Generated by Django 2.2 on 2019-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0023_case_checkdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='checked',
            field=models.CharField(max_length=10),
        ),
    ]
