# Generated by Django 2.2 on 2019-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0024_auto_20190612_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='addressSection',
            field=models.CharField(max_length=5),
        ),
    ]
