# Generated by Django 2.2 on 2019-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0025_auto_20190623_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='addressLatitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='case',
            name='addressLongitude',
            field=models.FloatField(default=0.0),
        ),
    ]
