# Generated by Django 2.2 on 2019-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefiles',
            name='address',
        ),
        migrations.RemoveField(
            model_name='casefiles',
            name='files',
        ),
        migrations.AddField(
            model_name='casefiles',
            name='path',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
