# Generated by Django 2.2 on 2019-05-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20190509_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefiles',
            name='case',
        ),
    ]
