# Generated by Django 2.2 on 2019-05-09 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_casefiles_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefiles',
            name='case',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='apply.Case'),
        ),
    ]
