# Generated by Django 2.2 on 2019-05-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0008_auto_20190509_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefiles',
            name='case',
        ),
    ]
