# Generated by Django 2.2 on 2019-05-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0009_remove_casefiles_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefiles',
            name='path',
            field=models.FilePathField(default='0'),
        ),
    ]
