# Generated by Django 2.2 on 2019-05-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_auto_20190509_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefiles',
            name='path',
            field=models.FileField(default='0', upload_to=''),
        ),
    ]
