# Generated by Django 2.2 on 2019-05-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0011_auto_20190509_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefiles',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
