# Generated by Django 2.2 on 2019-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0014_auto_20190623_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefiles',
            name='buildingDesignYear',
            field=models.CharField(default='undf', max_length=5),
        ),
        migrations.AlterField(
            model_name='casefiles',
            name='buildingHouseholdCount',
            field=models.CharField(default='undf', max_length=4),
        ),
    ]
