# Generated by Django 2.2 on 2019-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0015_auto_20190623_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefiles',
            name='photoCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
