# Generated by Django 2.2 on 2019-06-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0016_casefiles_photocount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casefiles',
            old_name='photoCount',
            new_name='jpegCount',
        ),
        migrations.AddField(
            model_name='casefiles',
            name='pngCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
