# Generated by Django 2.2 on 2019-06-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0017_auto_20190625_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefiles',
            name='buildingDesignYear',
            field=models.CharField(default='undf', max_length=10),
        ),
        migrations.AlterField(
            model_name='casefiles',
            name='buildingFloors',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='casefiles',
            name='buildingHouseholdCount',
            field=models.CharField(default='undf', max_length=10),
        ),
    ]
